sudo: required
language: python
services:
  - docker
env:
  global:
    - QUAY_REPO="quay.io/opentargets/platform-worker-service"
python:
  - 2.7
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - pytest --cov=app --cov-report term tests/ --fulltrace
notifications:
  email:
    recipients:
    - ops@opentargets.org
    on_success: never
    on_failure: always
addons:
  apt:
    packages:
    - gettext-base
    - jq
after_success:
  - codecov
  - docker pull "${QUAY_REPO}:${TRAVIS_BRANCH}" || true
  - docker build --pull --cache-from "${QUAY_REPO}:${TRAVIS_BRANCH}" --tag "${QUAY_REPO}" -f docker/Dockerfile .
  - docker login -u="${QUAY_USER}" -p="${QUAY_PASSWORD}" quay.io
  - git_sha="${TRAVIS_COMMIT}"
  - docker tag "${QUAY_REPO}" "${QUAY_REPO}:${TRAVIS_BRANCH}"
  - docker tag "${QUAY_REPO}" "${QUAY_REPO}:${git_sha}-${TRAVIS_BRANCH}"
  #only push non-PRs
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
      docker push "${QUAY_REPO}:${TRAVIS_BRANCH}" && docker push "${QUAY_REPO}:${git_sha}-${TRAVIS_BRANCH}"
      if [ "${TRAVIS_BRANCH}" = "master" ]; then
        docker tag "${QUAY_REPO}:${TRAVIS_BRANCH}" "${QUAY_REPO}:latest"
        docker push "${QUAY_REPO}:latest"
      fi
    fi
